config/urls.py
from django.contrib import admin
from django.urls import include, path    #変更

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hzyhyoka.urls')),                     #追加
    path('', include('accounts.urls')),                     #追加
    path('books/', include('books.urls')),                  #追加(books)
    path('kiki/', include('kiki.urls')),                    # 追加(kiki)
    path('excelupload/', include('excelupload.urls')),      # 追加(excelupload)
    path('exceldownload/', include('exceldownload.urls')),  # 追加(exceldownload)
    path('csvdownload/', include('csvdownload.urls')),      # 追加(exceldownload)
]

csvdownload/urls.py
from django.urls import path
from . import views

app_name = 'csvdownload'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('import/', views.PostImport.as_view(), name='import'),
    path('export/', views.PostExport, name='export'),
]

kiki/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.KikiList.as_view(), name='kiki'),
    path('<int:pk>/', views.KikiDetail.as_view(), name='detail'),
    path('create/', views.KikiCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.KikiUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.KikiDelete.as_view(), name='delete'),
    path('import/', views.KikiImport.as_view(), name='import'),
    path('export/', views.KikiExport, name='export'),
    path('downloadexcel/', views.KikiDownloadExcel, name='downloadexcel'),
    path('uploadexcel/', views.KikiUploadExcel.as_view(), name='uploadexcel'),
]

csvdownload/models.py
from django.db import models

class Post(models.Model):
    """役職マスタ"""
    name = models.CharField('役職名', max_length=50)

    def __str__(self):
        return self.name

csvdownload/forms.py
from django import forms

class CSVUploadForm(forms.Form):
    file = forms.FileField(label='CSVファイル')

csvdownload/views.py
import csv
import io
import urllib
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from .forms import CSVUploadForm
from .models import Post

# 役職テーブルの一覧表作成
class Index(generic.ListView):

    model = Post
    template_name = 'csvdownload/list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form_name'] = 'csvdownload'
        return ctx

# 役職テーブルの登録(csvアップロード)
class PostImport(generic.FormView):

    template_name = 'csvdownload/import.html'
    success_url = reverse_lazy('csvdownload:index')
    form_class = CSVUploadForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form_name'] = 'csvdownload'
        return ctx

    def form_valid(self, form):
        # """postされたCSVファイルを読み込み、役職テーブルに登録します"""
        csvfile = io.TextIOWrapper(form.cleaned_data['file'])
        reader = csv.reader(csvfile)
        for row in reader:
            # """
            # 役職テーブルを役職コード(primary key)で検索します
            # """
            post, created = Post.objects.get_or_create(pk=row[0])
            post.name = row[1]
            post.save()
        return super().form_valid(form)

# 役職テーブルを全件検索して、CSVファイルを作成してresponseに出力
def PostExport(request):

    response = HttpResponse(content_type='text/csv; charset=Shift-JIS')
    filename = urllib.parse.quote((u'CSVファイル.csv').encode("utf8"))
    response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'{}'.format(filename)
    writer = csv.writer(response)
    for post in Post.objects.all():
        writer.writerow([post.pk, post.name])
    return response

templates/csvdownload/import.html
{% extends 'commons/base.html' %}

{% block headertitle %}
CSVインポート
{% endblock %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  <p>ファイルを選択ボタンをクリックして、アップロードするCSVファイルを選択します</p>
  {% csrf_token %}
  <div class="form-group">
    {{form.file}}
  </div>
  <br/>
  <button type="submit">送信</button>
</form>
{% endblock %}

templates/csvdownload/list.html
{% extends 'commons/base.html' %}

{% block headertitle %}
CSVインポートエクスポート
{% endblock %}

{% block content %}
<div class="col-sm">
  <nav class="pull-right header">
      <ul id="menu">
        <li><a href="{% url 'csvdownload:import' %}" class="">インポート</a></li>
        <li><a href="{% url 'csvdownload:export' %}" class="">エクスポート</a></li>
      </ul>
  </nav>
</div>
<table class="table table-sm table-striped">
  <thead>
    <tr class="text-secondary bg-warning">
      <th class="" style="width:25%;">役職コード</th>
      <th class="">役職名</th>
    </tr>
  </thead>
  <tbody>
    {% for post in post_list %}
      <tr>
        <td>{{ post.pk }}</td>
        <td>{{ post.name }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}